# Configuration file for the Sphinx documentation builder.
# https://www.sphinx-doc.org/en/master/usage/configuration.html
# Generated by: ./iclaude.sh --init-docs

# -- Build command -------------------------------------------------------------
# sphinx-build -b html \
#   -d docs/sphinx/_build/.doctrees \
#   -c docs/sphinx \
#   docs/ docs/sphinx/_build/html
#
# This uses docs/ as source root so toctrees can reference
# architecture/, prd/, BACKUP_RESTORE.md, etc. directly.

# -- Project information -------------------------------------------------------
project = "familyBudget"
author = "familyBudget contributors"

# -- General configuration -----------------------------------------------------
extensions = [
    "myst_parser",
    "sphinx_design",
    "sphinx_copybutton",
    "sphinxcontrib.mermaid",
]

# sphinx-llms-txt: generates llms.txt and llms-full.txt for AI agents
# Install: pip install sphinx-llms-txt
try:
    import sphinx_llms_txt  # noqa: F401
    extensions.append("sphinx_llms_txt")
except ImportError:
    pass  # Optional — docs build without it

# MyST Parser — use Markdown with full Sphinx capabilities
myst_enable_extensions = [
    "colon_fence",   # ::: blocks as alternative to ``` for directives
    "deflist",       # Definition lists
    "fieldlist",     # Field lists
    "attrs_inline",  # Inline attributes {.class}
]

# Root document (relative to docs/ source root, where index.md lives in docs/sphinx/)
root_doc = "sphinx/index"

# File formats
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# Exclude patterns (relative to docs/ source root)
exclude_patterns = [
    "sphinx/_build",
    "sphinx/_build/**",
    "Thumbs.db",
    ".DS_Store",
    "**/.DS_Store",
    "diagrams/**",
    "plans/**",
    "testing/**",
    "guides/**",
]

# -- HTML output ---------------------------------------------------------------
html_theme = "furo"
html_title = "familyBudget Documentation"

# Furo theme options
html_theme_options = {
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
}

# -- sphinx-llms-txt -----------------------------------------------------------
# AI-first documentation: generates llms.txt and llms-full.txt
# These files allow AI agents to consume documentation efficiently
# See: https://llmstxt.org/
