listen_addresses = '*'
max_connections = 100                   # (change requires restart)
shared_buffers = 10MB                  # min 128kB
dynamic_shared_memory_type = posix      # the default is the first option
effective_io_concurrency = 200        # 1-1000; 0 disables prefetching
max_wal_size = 256MB
min_wal_size = 80MB
checkpoint_completion_target = 0.9
work_mem = 64MB
maintenance_work_mem = 128MB
shared_buffers = 64MB
autovacuum_vacuum_scale_factor = 0.02
autovacuum_vacuum_threshold = 50
autovacuum_max_workers = 5
temp_file_limit = '1GB'
log_timezone = 'Etc/UTC'
datestyle = 'iso, mdy'
timezone = 'Etc/UTC'
lc_messages = 'en_US.utf8'                      # locale for system error message
lc_monetary = 'en_US.utf8'                      # locale for monetary formatting
lc_numeric = 'en_US.utf8'                       # locale for number formatting
lc_time = 'en_US.utf8'                          # locale for time formatting
default_text_search_config = 'pg_catalog.english'
