const js = require("@eslint/js");
const tseslint = require("@typescript-eslint/eslint-plugin");
const tsparser = require("@typescript-eslint/parser");

module.exports = [
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      ".vite-build/**",
      "frontend/**/static/js/dist/**",
      "frontend/**/static/js/**/*.min.js",
      "frontend/shared/db/assets/**",
      "**/*.bundle.js",
      "coverage/**",
      ".npm-isolated/**",
      ".claude/**",
      "backend/**",
      "bot/**",
      "scripts/**",
      ".venv/**",
      "venv/**",
      "config/**",
      "*.config.js",
      "*.config.ts",
      "build-all.js",
      "sw.js",
      "sw.min.js",
      "**/*.min.js",
      "**/*.d.ts",
    ],
  },
  js.configs.recommended,
  {
    files: ["frontend/**/*.ts", "frontend/**/*.js"],
    languageOptions: {
      parser: tsparser,
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        WebSocket: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        IndexedDB: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        crypto: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        EventTarget: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        performance: "readonly",
        PerformanceObserver: "readonly",
        queueMicrotask: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        HTMLInputElement: "readonly",
        HTMLElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLFormElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLDivElement: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        Choices: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        // DOM types (for TypeScript interfaces used in code)
        Node: "readonly",
        Element: "readonly",
        RequestInit: "readonly",
        ResponseInit: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
    },
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "warn",
      "no-unused-vars": "off",  // Disabled in favor of @typescript-eslint/no-unused-vars
      "no-undef": "warn",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "warn",
      "prefer-const": "warn",
      "no-var": "warn",
      "no-useless-catch": "warn",
      "no-inner-declarations": "warn",
      "no-prototype-builtins": "warn",
      "no-case-declarations": "warn",
      "no-empty": "warn",
      "no-redeclare": "warn",
      "no-dupe-class-members": "warn",
      "no-fallthrough": "warn",
      "no-constant-condition": "warn",
      "no-useless-escape": "warn",
      "no-cond-assign": "warn",
      "no-self-assign": "warn",
      "no-dupe-else-if": "warn",
      "no-extra-boolean-cast": "warn",
      "no-extra-semi": "warn",
    },
  },
];
