credentials:
  usernames:
    ilya:
      name: ilya
      password: ilya # To be replaced with hashed password
    oksana:
      name: oksana
      password: oksana # To be replaced with hashed password
cookie:
  expiry_days: 1
  key: K4mfHNkS9gxcF68dRELC # Must be string
  name: ikeniborn_cookie