version: '2.4'

services:
  budget:
    container_name: budget
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:443'
    volumes:
      - '/home/bagatocorp/web/app:/usr/src/app:delegated'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - BUDGET_POSTGRES_HOST=10.5.0.3
      - BUDGET_POSTGRES_PORT=5432
      - BUDGET_POSTGRES_DB=budgetdb
      - BUDGET_POSTGRES_USER=budget
      - BUDGET_POSTGRES_PASSWORD=4phDukPGF7sUWSEvfycX
      - GOOGLE_STORAGE_CREDENTIAL_PATH=/usr/src/app/secrets/bagato-403919-f547cd93bfb2.json
    networks:
      app_network:
        ipv4_address: 10.5.0.2
    healthcheck:
      test: ["CMD", "curl","--cacert","/usr/src/app/cert/budget.ikeniborn.ru.pem","--fail","https://budget.ikeniborn.ru:443/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: "postgres:13"
    networks:
      app_network:
        ipv4_address: 10.5.0.3
    environment:
      POSTGRES_DB: budgetdb
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: 4phDukPGF7sUWSEvfycX
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      # - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget -d budgetdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  postgres-data:
    driver: local

