"""Medicine intake log — one row per scheduled dose."""
from datetime import datetime
from decimal import Decimal

from sqlalchemy import UniqueConstraint
from sqlmodel import Field, SQLModel


class MedicineIntakeLog(SQLModel, table=True):
    """A single scheduled (and possibly taken/skipped) dose. Generated by the maintenance job."""

    __tablename__ = "t_f_medicine_intake_log"
    __table_args__ = (
        UniqueConstraint("course_id", "scheduled_at", name="uq_intake_course_scheduled"),
    )

    id: int | None = Field(default=None, primary_key=True)
    course_id: int = Field(foreign_key="t_f_medicine_course.id", index=True, nullable=False)
    patient_id: int = Field(foreign_key="t_d_family_member.id", index=True, nullable=False,
                            description="Denormalized for (patient_id, scheduled_at) filter without join")
    scheduled_at: datetime = Field(nullable=False, description="Planned time (naive, SYSTEM_TIMEZONE)")
    taken_at: datetime | None = Field(default=None, description="Actual intake time (NULL = not marked)")
    status: str = Field(default="scheduled", nullable=False, max_length=20,
                        description="scheduled/taken/skipped/late")
    dose_taken: Decimal | None = Field(default=None, max_digits=10, decimal_places=3)
    stock_id: int | None = Field(default=None, foreign_key="t_f_medicine_stock.id",
                                 description="Package the dose was deducted from (Phase 4)")
    comment: str | None = Field(default=None)
    marked_by: int | None = Field(default=None, foreign_key="t_d_user.id",
                                  description="Who marked it (parent for a child)")
    version: int = Field(default=1, nullable=False, description="Optimistic locking for concurrent marks")
    created_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)
    updated_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)
