-- ============================================================================
-- INSERT: t_d_article_hierarchy (Closure Table)
-- Description: Article hierarchy relationships
-- Generated: 2025-11-02 12:32:07
-- ============================================================================

-- Insert hierarchy relationships (ancestor-descendant pairs)
-- Self-references (depth=0) are auto-created by trigger
-- Here we only insert parent-child relationships (depth=1)
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Зарплата' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Аванс' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Медицина, аптека' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Аптека' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Топливо' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Бензин' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Вещи' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Вещи' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Возврат' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Возврат' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Гипермаркет' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Детские товары' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Топливо' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Дизель' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Коммунальные платежи' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'ЖКХ' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Ремонт и обсуживание' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Запчасти' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Зарплата' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Зарплата' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Коммунальные платежи' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Капремонт' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Кафе и рестораны' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Кафе' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Аренда' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Квартира' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Гипермаркет' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Корм для животных' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Красота и здоровье' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Косметика' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Красота и здоровье' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Красота' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Ремонт и обсуживание' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Мебель' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Медицина, аптека' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Медицина' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Мобильная связь, интернет, ТВ' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Мобильная связь' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Штрафы, налоги, комиссии' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Налоги' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Одежда и обувь' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Обувь' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'ПО, книги и журналы, игры, музыка, фильмы' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Обучение' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Одежда и обувь' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Одежда' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Вещи' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Одежда и обувь' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Зарплата' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Отпускные' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Перевод на счет Семья' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Перевод на счет Семья' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'ПО, книги и журналы, игры, музыка, фильмы' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Платные подписки' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Подарки' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Подарки' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Возврат' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Пополнение' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Биржа' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Пополнение биржи' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Цели' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Пополнение целей' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Развлечения и праздники' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Праздники' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Зарплата' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Премия' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Доходы' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Приход со счета Илья' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Доходы' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Приход со счета Оксана' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'ПО, книги и журналы, игры, музыка, фильмы' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Программы' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Продажа' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Продажа' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Гипермаркет' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Продукты' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Депозит' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Проценты' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Прочее' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Прочее' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Развлечения и праздники' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Развлечения' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Кафе и рестораны' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Ресторан' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Сигареты и табак' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Сигареты' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Гипермаркет' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Столовая' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Ремонт и обсуживание' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Строительные материалы' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Сигареты и табак' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Табак' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Общественный транспорт' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Такси' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Остатки' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Текущие остатки' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Бытовая техника, электроника' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Техника и электроника' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Гипермаркет' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Товары' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Общественный транспорт' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Трамвай' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Долги' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Увеличение долга' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Займы' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Увеличение займа' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Накопления' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Увеличение накоплений' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Долги' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Уменьшение долга' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Займы' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Уменьшение займа' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Накопления' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Уменьшение накоплений' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Услуги' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Услуги по обсуживанию' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Услуги' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Услуги по ремонту' AND is_current = true LIMIT 1), 1);
INSERT INTO t_d_article_hierarchy (ancestor_id, descendant_id, depth) VALUES ((SELECT id FROM t_d_article WHERE name = 'Штрафы, налоги, комиссии' AND is_current = true LIMIT 1), (SELECT id FROM t_d_article WHERE name = 'Штрафы' AND is_current = true LIMIT 1), 1);

-- Total: 60 parent-child relationships