"""Add article table and update nomenclature with article_id

Revision ID: db5be6413a0c
Revises: ba29b9c1f48d
Create Date: 2025-09-15 20:55:11.787059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db5be6413a0c'
down_revision: Union[str, None] = 'ba29b9c1f48d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create t_d_article table
    op.create_table('t_d_article',
        sa.Column('article_id', sa.Integer(), nullable=False),
        sa.Column('article_code', sa.String(length=50), nullable=False),
        sa.Column('article_name', sa.String(), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('managed_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['t_d_user.user_id'], name=op.f('fk_t_d_article_created_by_t_d_user')),
        sa.ForeignKeyConstraint(['managed_by'], ['t_d_user.user_id'], name=op.f('fk_t_d_article_managed_by_t_d_user')),
        sa.PrimaryKeyConstraint('article_id', name=op.f('pk_t_d_article')),
        sa.UniqueConstraint('article_code', name=op.f('uq_t_d_article_article_code'))
    )
    op.create_index(op.f('ix_t_d_article_article_id'), 't_d_article', ['article_id'], unique=False)
    op.create_index(op.f('ix_t_d_article_user_id'), 't_d_article', ['user_id'], unique=False)

    # Insert initial shared articles data
    articles_table = sa.table('t_d_article',
        sa.column('article_code', sa.String),
        sa.column('article_name', sa.String),
        sa.column('description', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('user_id', sa.Integer),
        sa.column('created_by', sa.Integer),
        sa.column('managed_by', sa.Integer)
    )

    op.bulk_insert(articles_table, [
        {'article_code': 'HOUSEHOLD', 'article_name': 'Домашние расходы', 'description': 'Товары для дома и быта', 'is_active': True, 'user_id': None, 'created_by': None, 'managed_by': None},
        {'article_code': 'TRANSPORT', 'article_name': 'Транспорт', 'description': 'Транспортные расходы', 'is_active': True, 'user_id': None, 'created_by': None, 'managed_by': None},
        {'article_code': 'FOOD', 'article_name': 'Питание', 'description': 'Продукты питания и еда', 'is_active': True, 'user_id': None, 'created_by': None, 'managed_by': None},
        {'article_code': 'UTILITIES', 'article_name': 'Коммунальные услуги', 'description': 'ЖКХ и коммунальные платежи', 'is_active': True, 'user_id': None, 'created_by': None, 'managed_by': None},
        {'article_code': 'ENTERTAINMENT', 'article_name': 'Развлечения', 'description': 'Досуг и развлечения', 'is_active': True, 'user_id': None, 'created_by': None, 'managed_by': None},
        {'article_code': 'HEALTHCARE', 'article_name': 'Здравоохранение', 'description': 'Медицинские услуги и лекарства', 'is_active': True, 'user_id': None, 'created_by': None, 'managed_by': None},
        {'article_code': 'EDUCATION', 'article_name': 'Образование', 'description': 'Обучение и образовательные услуги', 'is_active': True, 'user_id': None, 'created_by': None, 'managed_by': None},
        {'article_code': 'INCOME_SALARY', 'article_name': 'Зарплата', 'description': 'Доходы от основной работы', 'is_active': True, 'user_id': None, 'created_by': None, 'managed_by': None},
        {'article_code': 'INCOME_BUSINESS', 'article_name': 'Бизнес', 'description': 'Доходы от предпринимательской деятельности', 'is_active': True, 'user_id': None, 'created_by': None, 'managed_by': None},
        {'article_code': 'INCOME_INVESTMENT', 'article_name': 'Инвестиции', 'description': 'Доходы от инвестиций', 'is_active': True, 'user_id': None, 'created_by': None, 'managed_by': None}
    ])
    op.alter_column('t_d_cost_center', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('t_d_cost_center', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('_cost_center_code_uc', 't_d_cost_center', type_='unique')
    op.drop_index('idx_cost_center_name_system_unique', table_name='t_d_cost_center', postgresql_where='(user_id IS NULL)')
    op.drop_index('idx_cost_center_name_user_unique', table_name='t_d_cost_center', postgresql_where='(user_id IS NOT NULL)')
    op.drop_index('idx_cost_center_user_id', table_name='t_d_cost_center')
    op.create_index(op.f('ix_t_d_cost_center_user_id'), 't_d_cost_center', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_t_d_cost_center_cost_center_code'), 't_d_cost_center', ['cost_center_code'])
    op.alter_column('t_d_financial_center', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('t_d_financial_center', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('_financial_center_code_uc', 't_d_financial_center', type_='unique')
    op.drop_index('idx_financial_center_name_system_unique', table_name='t_d_financial_center', postgresql_where='(user_id IS NULL)')
    op.drop_index('idx_financial_center_name_user_unique', table_name='t_d_financial_center', postgresql_where='(user_id IS NOT NULL)')
    op.drop_index('idx_financial_center_user_id', table_name='t_d_financial_center')
    op.create_index(op.f('ix_t_d_financial_center_user_id'), 't_d_financial_center', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_t_d_financial_center_financial_center_code'), 't_d_financial_center', ['financial_center_code'])
    op.add_column('t_d_nomenclature', sa.Column('article_id', sa.Integer(), nullable=True))
    op.alter_column('t_d_nomenclature', 'nomenclature_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('INCOME', 'EXPENSE', name='nomenclaturetype'),
               existing_nullable=True,
               existing_server_default=sa.text("'EXPENSE'::character varying"))
    op.alter_column('t_d_nomenclature', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('t_d_nomenclature', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('_nomenclature_code_uc', 't_d_nomenclature', type_='unique')
    op.drop_index('idx_nomenclature_name_system_unique', table_name='t_d_nomenclature', postgresql_where='(user_id IS NULL)')
    op.drop_index('idx_nomenclature_name_user_unique', table_name='t_d_nomenclature', postgresql_where='(user_id IS NOT NULL)')
    op.drop_index('idx_nomenclature_parent_id', table_name='t_d_nomenclature')
    op.drop_index('idx_nomenclature_user_id', table_name='t_d_nomenclature')
    op.create_index(op.f('ix_t_d_nomenclature_parent_id'), 't_d_nomenclature', ['parent_id'], unique=False)
    op.create_index(op.f('ix_t_d_nomenclature_user_id'), 't_d_nomenclature', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_t_d_nomenclature_nomenclature_code'), 't_d_nomenclature', ['nomenclature_code'])
    op.create_foreign_key(op.f('fk_t_d_nomenclature_article_id_t_d_article'), 't_d_nomenclature', 't_d_article', ['article_id'], ['article_id'])
    op.drop_constraint('_period_code_uc', 't_d_period', type_='unique')
    op.drop_constraint('unique_period_date_user', 't_d_period', type_='unique')
    op.create_unique_constraint(op.f('uq_t_d_period_period_code'), 't_d_period', ['period_code'])
    op.drop_constraint('fk_t_d_period_user_id_t_d_user', 't_d_period', type_='foreignkey')
    op.alter_column('t_d_sharing', 'created_dttm',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('t_d_sharing', 'updated_dttm',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_t_d_sharing_active', table_name='t_d_sharing', postgresql_where='(is_active = true)')
    op.drop_index('ix_t_d_sharing_owner_resource', table_name='t_d_sharing')
    op.drop_index('ix_t_d_sharing_owner_user_id', table_name='t_d_sharing')
    op.drop_index('ix_t_d_sharing_resource_type', table_name='t_d_sharing')
    op.drop_index('ix_t_d_sharing_shared_resource', table_name='t_d_sharing')
    op.drop_index('ix_t_d_sharing_shared_with_user_id', table_name='t_d_sharing')
    op.drop_constraint('uq_t_d_sharing_owner_shared_resource', 't_d_sharing', type_='unique')
    op.create_index(op.f('ix_t_d_sharing_sharing_id'), 't_d_sharing', ['sharing_id'], unique=False)
    op.drop_index('ix_t_d_user_user_role', table_name='t_d_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop t_d_article table
    op.drop_index(op.f('ix_t_d_article_user_id'), table_name='t_d_article')
    op.drop_index(op.f('ix_t_d_article_article_id'), table_name='t_d_article')
    op.drop_table('t_d_article')
    op.create_index('ix_t_d_user_user_role', 't_d_user', ['user_role'], unique=False)
    op.drop_index(op.f('ix_t_d_sharing_sharing_id'), table_name='t_d_sharing')
    op.create_unique_constraint('uq_t_d_sharing_owner_shared_resource', 't_d_sharing', ['owner_user_id', 'shared_with_user_id', 'resource_type', 'resource_id'])
    op.create_index('ix_t_d_sharing_shared_with_user_id', 't_d_sharing', ['shared_with_user_id'], unique=False)
    op.create_index('ix_t_d_sharing_shared_resource', 't_d_sharing', ['shared_with_user_id', 'resource_type'], unique=False)
    op.create_index('ix_t_d_sharing_resource_type', 't_d_sharing', ['resource_type'], unique=False)
    op.create_index('ix_t_d_sharing_owner_user_id', 't_d_sharing', ['owner_user_id'], unique=False)
    op.create_index('ix_t_d_sharing_owner_resource', 't_d_sharing', ['owner_user_id', 'resource_type'], unique=False)
    op.create_index('ix_t_d_sharing_active', 't_d_sharing', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('t_d_sharing', 'updated_dttm',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('t_d_sharing', 'created_dttm',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('fk_t_d_period_user_id_t_d_user', 't_d_period', 't_d_user', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('uq_t_d_period_period_code'), 't_d_period', type_='unique')
    op.create_unique_constraint('unique_period_date_user', 't_d_period', ['period_dt', 'user_id'])
    op.create_unique_constraint('_period_code_uc', 't_d_period', ['period_code'])
    op.drop_constraint(op.f('fk_t_d_nomenclature_article_id_t_d_article'), 't_d_nomenclature', type_='foreignkey')
    op.drop_constraint(op.f('uq_t_d_nomenclature_nomenclature_code'), 't_d_nomenclature', type_='unique')
    op.drop_index(op.f('ix_t_d_nomenclature_user_id'), table_name='t_d_nomenclature')
    op.drop_index(op.f('ix_t_d_nomenclature_parent_id'), table_name='t_d_nomenclature')
    op.create_index('idx_nomenclature_user_id', 't_d_nomenclature', ['user_id'], unique=False)
    op.create_index('idx_nomenclature_parent_id', 't_d_nomenclature', ['parent_id'], unique=False)
    op.create_index('idx_nomenclature_name_user_unique', 't_d_nomenclature', ['nomenclature_name', 'user_id'], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.create_index('idx_nomenclature_name_system_unique', 't_d_nomenclature', ['nomenclature_name'], unique=False, postgresql_where='(user_id IS NULL)')
    op.create_unique_constraint('_nomenclature_code_uc', 't_d_nomenclature', ['nomenclature_code'])
    op.alter_column('t_d_nomenclature', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('t_d_nomenclature', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('t_d_nomenclature', 'nomenclature_type',
               existing_type=sa.Enum('INCOME', 'EXPENSE', name='nomenclaturetype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'EXPENSE'::character varying"))
    op.drop_column('t_d_nomenclature', 'article_id')
    op.drop_constraint(op.f('uq_t_d_financial_center_financial_center_code'), 't_d_financial_center', type_='unique')
    op.drop_index(op.f('ix_t_d_financial_center_user_id'), table_name='t_d_financial_center')
    op.create_index('idx_financial_center_user_id', 't_d_financial_center', ['user_id'], unique=False)
    op.create_index('idx_financial_center_name_user_unique', 't_d_financial_center', ['financial_center_name', 'user_id'], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.create_index('idx_financial_center_name_system_unique', 't_d_financial_center', ['financial_center_name'], unique=False, postgresql_where='(user_id IS NULL)')
    op.create_unique_constraint('_financial_center_code_uc', 't_d_financial_center', ['financial_center_code'])
    op.alter_column('t_d_financial_center', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('t_d_financial_center', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('uq_t_d_cost_center_cost_center_code'), 't_d_cost_center', type_='unique')
    op.drop_index(op.f('ix_t_d_cost_center_user_id'), table_name='t_d_cost_center')
    op.create_index('idx_cost_center_user_id', 't_d_cost_center', ['user_id'], unique=False)
    op.create_index('idx_cost_center_name_user_unique', 't_d_cost_center', ['cost_center_name', 'user_id'], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.create_index('idx_cost_center_name_system_unique', 't_d_cost_center', ['cost_center_name'], unique=False, postgresql_where='(user_id IS NULL)')
    op.create_unique_constraint('_cost_center_code_uc', 't_d_cost_center', ['cost_center_code'])
    op.alter_column('t_d_cost_center', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('t_d_cost_center', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
