/**
 * Recurring Plan operations (CRUD + Queries)
 * Lightweight reference data без pending operations queue
 */

import { db, toCents, fromCents } from '../core/database';
import { logger } from '../utils/logger';
import type {
  LocalRecurringPlan
} from '../types/fact';

/**
 * Filters for querying recurring plans
 */
export interface RecurringPlanFilters {
  user_id?: number;
  article_id?: number;
  financial_center_id?: number;
  cost_center_id?: number;
  is_active?: boolean;
  frequency?: string;
  from_date?: string;  // Filter by next_generation_date >= from_date (YYYY-MM-DD) - v11.4.0+
  to_date?: string;    // Filter by next_generation_date <= to_date (YYYY-MM-DD) - v11.4.0+
}

/**
 * Query recurring plans с фильтрацией
 *
 * @param filters - Optional filters
 * @returns Array of recurring plans
 */
export async function queryRecurringPlans(filters?: RecurringPlanFilters): Promise<LocalRecurringPlan[]> {
  logger.debug('[Dexie] queryRecurringPlans', filters);

  let results: LocalRecurringPlan[];

  // Optimization: use user_id index if available
  if (filters?.user_id) {
    results = await db.recurringPlans
      .where('user_id')
      .equals(filters.user_id)
      .toArray();
  } else {
    // Fallback: load all и filter в памяти
    results = await db.recurringPlans.toArray();
  }

  // Apply additional filters
  if (filters) {
    results = results.filter(plan => {
      if (filters.user_id && plan.user_id !== filters.user_id) return false;
      if (filters.article_id && plan.article_id !== filters.article_id) return false;
      if (filters.financial_center_id && plan.financial_center_id !== filters.financial_center_id) return false;
      if (filters.cost_center_id && plan.cost_center_id !== filters.cost_center_id) return false;
      if (filters.is_active !== undefined && plan.is_active !== filters.is_active) return false;
      if (filters.frequency && plan.frequency !== filters.frequency) return false;

      // Date filtering (v11.4.0+)
      if (filters.from_date && plan.next_generation_date < filters.from_date) return false;
      if (filters.to_date && plan.next_generation_date > filters.to_date) return false;

      return true;
    });
  }

  // Convert amount from cents to dollars
  return results.map(plan => ({
    ...plan,
    amount: fromCents(plan.amount)
  }));
}

/**
 * Create recurring plan
 * ВАЖНО: amount конвертируется в cents
 *
 * @param plan - Recurring plan data (without id, created_at)
 * @returns created plan id
 */
export async function createRecurringPlan(
  plan: Omit<LocalRecurringPlan, 'id' | 'created_at'>
): Promise<number> {
  try {
    logger.debug('[Dexie] Creating recurring plan', plan);

    // Validate required fields
    if (!plan.user_id || !plan.article_id || !plan.financial_center_id || !plan.amount || !plan.frequency) {
      throw new Error('[Dexie] Missing required fields for recurring plan');
    }

    // Convert amount to cents
    const newPlan: LocalRecurringPlan = {
      ...plan,
      id: 0, // Will be auto-generated by Dexie
      amount: toCents(plan.amount),
      created_at: new Date()
    };

    // Insert plan
    const id = await db.recurringPlans.add(newPlan);

    logger.info('[Dexie] ✅ Recurring plan created', { id });

    return id as number;
  } catch (error) {
    logger.error('[Dexie] ❌ Recurring plan create error:', error);
    throw error;
  }
}

/**
 * Update recurring plan
 *
 * @param id - Plan id
 * @param updates - Partial plan data to update
 */
export async function updateRecurringPlan(
  id: number,
  updates: Partial<Omit<LocalRecurringPlan, 'id' | 'created_at'>>
): Promise<void> {
  try {
    logger.debug('[Dexie] Updating recurring plan', { id, updates });

    // Get existing plan
    const plan = await db.recurringPlans.get(id);

    if (!plan) {
      throw new Error(`[Dexie] Recurring plan not found: ${id}`);
    }

    // Convert amount to cents if provided
    const updateData = { ...updates };
    if (updateData.amount !== undefined) {
      updateData.amount = toCents(updateData.amount);
    }

    // Update plan
    await db.recurringPlans.update(id, updateData);

    logger.info('[Dexie] ✅ Recurring plan updated', { id });
  } catch (error) {
    logger.error('[Dexie] ❌ Recurring plan update error:', error);
    throw error;
  }
}

/**
 * Delete recurring plan
 *
 * @param id - Plan id
 */
export async function deleteRecurringPlan(id: number): Promise<void> {
  try {
    logger.debug('[Dexie] Deleting recurring plan', { id });

    // Delete plan
    await db.recurringPlans.delete(id);

    logger.info('[Dexie] ✅ Recurring plan deleted', { id });
  } catch (error) {
    logger.error('[Dexie] ❌ Recurring plan delete error:', error);
    throw error;
  }
}

/**
 * Get single recurring plan by id
 *
 * @param id - Plan id
 * @returns Recurring plan or undefined
 */
export async function getRecurringPlan(id: number): Promise<LocalRecurringPlan | undefined> {
  try {
    logger.debug('[Dexie] Getting recurring plan', { id });

    const plan = await db.recurringPlans.get(id);

    if (!plan) {
      return undefined;
    }

    // Convert amount from cents to dollars
    return {
      ...plan,
      amount: fromCents(plan.amount)
    };
  } catch (error) {
    logger.error('[Dexie] ❌ Get recurring plan error:', error);
    throw error;
  }
}

/**
 * Sync recurring plans from server
 * Replaces local data with server version
 *
 * @param plans - Array of recurring plans from server
 */
export async function syncRecurringPlansFromServer(plans: LocalRecurringPlan[]): Promise<void> {
  try {
    logger.debug('[Dexie] Syncing recurring plans from server', { count: plans.length });

    // Convert amounts to cents
    const plansWithCents = plans.map(plan => ({
      ...plan,
      amount: toCents(plan.amount)
    }));

    // Replace all local data (clear + bulk add)
    await db.transaction('rw', db.recurringPlans, async () => {
      await db.recurringPlans.clear();
      await db.recurringPlans.bulkAdd(plansWithCents);
    });

    logger.info('[Dexie] ✅ Recurring plans synced from server', { count: plans.length });
  } catch (error) {
    logger.error('[Dexie] ❌ Sync recurring plans error:', error);
    throw error;
  }
}
