name: Release Drafter

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission for contents to create/update releases
      contents: write
      # write permission for pull-requests to add labels
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
