version: "3"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: "postgres:13"
    networks:
      app_network:
        ipv4_address: 10.5.0.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2PoMNcdzxkbVjJerquRQ
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ${APP_PATH}/app/web/db/postgresql/postgresql.conf:/var/lib/postgresql/data/pgdata/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    cpuset: "0"    
    cpus: 0.5  
    mem_reservation: "100M"
    mem_limit: "250M" 
    depends_on:
      - haproxy

  budget-api:
    container_name: budget-api
    hostname: budget-api
    build:
      dockerfile: ./api/Dockerfile
      context: ./
    volumes:
      - ${APP_PATH}/app/web/api:/usr/src/app:delegated
    ports:
      - "8888:8888"
    command: "uvicorn budget_api:app --host 0.0.0.0 --port 8888 --reload"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - POSTGRES_HOST=10.5.0.2
      - POSTGRES_PORT=5432
      - POSTGRES_DB=budgetdb
      - POSTGRES_USER=budget
      - POSTGRES_PASSWORD=VZ7TcYGrb3jvJAFRQSsg
    networks:
      app_network:
        ipv4_address: 10.5.0.3
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/0.0.0.0/8888"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    cpuset: "0"    
    cpus: 0.25 
    mem_reservation: "100M"
    mem_limit: "250M" 
    depends_on:
      - postgres
      - haproxy

  budget-ui:
    container_name: budget-ui
    hostname: budget-ui
    build:
      dockerfile: ./app/budget/Dockerfile
      context: ./
    volumes:
      - ${APP_PATH}/app/web/app/budget:/usr/src/app:delegated
    ports:
      - "8501:8501"
    command: "streamlit run ui.py --server.port=8501"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - API_URL=http://10.5.0.3:8888
      - POLARS_SKIP_CPU_CHECK=false
    networks:
      app_network:
        ipv4_address: 10.5.0.4
    healthcheck:
      test: ["CMD", "curl","--fail","http://0.0.0.0:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    cpuset: "0"    
    cpus: 0.25 
    mem_reservation: "100M"
    mem_limit: "250M" 
    depends_on:
      - budget-api
      - haproxy

  haproxy:
    container_name: haproxy
    hostname: haproxy
    image: "haproxy:2.2-alpine"
    volumes:
      - ${APP_PATH}/app/web/service/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:delegated
      - /etc/haproxy/certs:/etc/ssl/certs:delegated
    network_mode: "host"
    restart: always
    cpuset: "0"    
    mem_reservation: "50M"
    mem_limit: "100M" 
    cpus: 0.1

  crm:
    container_name: crm
    image: nocobase/nocobase:latest
    networks:
      app_network:
        ipv4_address: 10.5.0.5
    environment:
      # The application's secret key, used to generate user tokens, etc.
      # If APP_KEY is changed, old tokens will also become invalid.
      # It can be any random string, and make sure it is not exposed.
      - APP_KEY=4+/D+3FWCK2T+PbwSdtEYAhmPjBTVYYRGbNsK5ctDyND3XOlFuIYTk1P
      # Database type, supports postgres, mysql, mariadb
      - DB_DIALECT=postgres
      # Database host, can be replaced with the IP of an existing database server
      - DB_HOST=10.5.0.2
      # Database name
      - DB_DATABASE=crm
      # Database user
      - DB_USER=crm
      # Database password
      - DB_PASSWORD=Ke39GbrtjRoYhVpyXxkW
      # Timezone
      - TZ=Europe/Moscow
      # Application environment
      - APP_ENV=production
      - APP_PORT=13000
      - API_BASE_PATH=/api/
      - CACHE_DEFAULT_STORE=memory
      - CACHE_MEMORY_MAX=100
      - INIT_ROOT_EMAIL=admin@ikeniborn.ru
      - INIT_ROOT_PASSWORD=XGjYnPcNKaz49qELdZrk
      - INIT_ROOT_NICKNAME=Admin
      - INIT_APP_LANG=en-US
      - APP_PUBLIC_PATH=
      - API_KEY=yAKU9jsGotfQ423z
    volumes:
      - crm-data:/app/nocobase/storage
    ports:
      - "13000:13000"
    depends_on:
      - postgres
      - haproxy
    cpuset: "0"    
    cpus: 0.5
    mem_reservation: "500M"
    mem_limit: "1000M" 

  couchdb:
      image: couchdb:latest
      hostname: couchdb
      container_name: couchdb
      networks:
        app_network:
          ipv4_address: 10.5.0.6
      ports:
          - "5984:5984"
      environment:
          - COUCHDB_USER=admin
          - COUCHDB_PASSWORD=2L6uEoNMjW9rVnPgy37t
      volumes:
          - couchdb-data:/opt/couchdb/data
          - ${APP_PATH}/app/web/db/couchdb/local.ini:/opt/couchdb/etc/local.ini
      restart: always
      cpuset: "0"    
      cpus: 0.25
      mem_reservation: "25M"
      mem_limit: "100M" 

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  postgres-data:
    driver: local
  couchdb-data:
    driver: local
  crm-data:
    driver: local

