
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: "postgres:13"
    networks:
      app_network:
        ipv4_address: 10.5.0.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2PoMNcdzxkbVjJerquRQ
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  api:
    container_name: api
    hostname: api
    build:
      dockerfile: ./app/api/Dockerfile
      context: ./
    volumes:
      - /home/bagatocorp/web/app/api:/usr/src/app:delegated
    ports:
      - "8888:8888"
    command: "uvicorn api:app --host 0.0.0.0 --port 8888 --reload"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - POSTGRES_HOST=10.5.0.2
      - POSTGRES_PORT=5432
      - BUDGET_POSTGRES_DB=budgetdb
      - BUDGET_POSTGRES_USER=budget
      - BUDGET_POSTGRES_PASSWORD=VZ7TcYGrb3jvJAFRQSsg
      - PORTFOLIO_POSTGRES_DB=portfoliodb
      - PORTFOLIO_POSTGRES_USER=portfolio
      - PORTFOLIO_POSTGRES_PASSWORD=ZC9eKnpEDvuWQgHUt8cx
    networks:
      app_network:
        ipv4_address: 10.5.0.3
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/0.0.0.0/8888"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      - postgres

  budget-ui:
    container_name: budget-ui
    hostname: budget-ui
    build:
      dockerfile: ./app/budget/Dockerfile
      context: ./
    volumes:
      - /home/bagatocorp/web/app/budget:/usr/src/app:delegated
    ports:
      - "8501:8501"
    command: "streamlit run ui.py --server.port=8501"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - API_URL=http://10.5.0.3:8888
      - POLARS_SKIP_CPU_CHECK=false
    networks:
      app_network:
        ipv4_address: 10.5.0.4
    healthcheck:
      test: ["CMD", "curl","--fail","http://0.0.0.0:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      - api

  haproxy:
    container_name: haproxy
    hostname: haproxy
    image: "haproxy:2.2-alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/bagatocorp/web/service/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:delegated
      - /home/bagatocorp/web/service/haproxy/certs:/etc/ssl/certs:delegated
    networks:
      app_network:
        ipv4_address: 10.5.0.10
    depends_on:
      - budget-ui

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  postgres-data:
    driver: local

